theme: null

plugins:
  - jekyll-seo-tag
  - jekyll-feed

minima:
  skin: auto
  social_links:
    - title: Vera Golz at LinkedIn
      icon: square-linkedin
      url: "https://www.linkedin.com/in/vera-golz-9a158b253/"
  nav_pages:
    - README.md
